server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xyz?serverTimezone=GMT%2B8
    username: root
    password: 12345678xh
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/api/*Mapper.xml
